In [1]:
import pandas as pd
import dask.dataframe as dd

In [880]:
variable = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/PATIENTS.csv")
variable.dtypes

ROW_ID          int64
SUBJECT_ID      int64
GENDER         object
DOB            object
DOD            object
DOD_HOSP       object
DOD_SSN        object
EXPIRE_FLAG     int64
dtype: object

In [881]:
variable['GENDER'].isna().sum() 
variable['GENDER'].value_counts()

M    26121
F    20399
Name: GENDER, dtype: int64

In [882]:
variable1 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/LABEVENTS.csv")
#variable1.dtypes

In [883]:
variable2 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/PROCEDURES_ICD.csv")
#variable2.dtypes

In [884]:
variable3 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/PRESCRIPTIONS.csv")
variable3.dtypes

/Users/savitha/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

ROW_ID                 int64
SUBJECT_ID             int64
HADM_ID                int64
ICUSTAY_ID           float64
STARTDATE             object
ENDDATE               object
DRUG_TYPE             object
DRUG                  object
DRUG_NAME_POE         object
DRUG_NAME_GENERIC     object
FORMULARY_DRUG_CD     object
GSN                   object
NDC                  float64
PROD_STRENGTH         object
DOSE_VAL_RX           object
DOSE_UNIT_RX          object
FORM_VAL_DISP         object
FORM_UNIT_DISP        object
ROUTE                 object
dtype: object

In [885]:
variable4 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/DIAGNOSES_ICD.csv")
#variable4.dtypes

In [886]:
variable5 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/D_LABITEMS.csv")
#variable5.dtypes

In [887]:
variable6 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/ADMISSIONS.csv")
#variable6.dtypes

In [888]:
variable6['ETHNICITY'].isna().sum()

0

In [889]:
variable6['ADMISSION_LOCATION'].isna().sum() 
variable6['ADMISSION_LOCATION'].value_counts()
# Making a list of missing value types
missing_values = ["** INFO NOT AVAILABLE **"]
variable6 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/ADMISSIONS.csv", na_values = missing_values)

In [890]:
variable6['ADMISSION_LOCATION'].isna().sum() 
variable6['ADMISSION_LOCATION'].value_counts()

EMERGENCY ROOM ADMIT         22754
PHYS REFERRAL/NORMAL DELI    15079
CLINIC REFERRAL/PREMATURE    12032
TRANSFER FROM HOSP/EXTRAM     8456
TRANSFER FROM SKILLED NUR      273
HMO REFERRAL/SICK              102
TRANSFER FROM OTHER HEALT       71
TRSF WITHIN THIS FACILITY        5
Name: ADMISSION_LOCATION, dtype: int64

In [891]:
# Replace using median 
#median = variable6['ADMISSION_LOCATION'].median()
variable6['ADMISSION_LOCATION'].fillna("CLINIC REFERRAL/PREMATURE", inplace=True)
variable6['ADMISSION_LOCATION'].value_counts()

EMERGENCY ROOM ADMIT         22754
PHYS REFERRAL/NORMAL DELI    15079
CLINIC REFERRAL/PREMATURE    12236
TRANSFER FROM HOSP/EXTRAM     8456
TRANSFER FROM SKILLED NUR      273
HMO REFERRAL/SICK              102
TRANSFER FROM OTHER HEALT       71
TRSF WITHIN THIS FACILITY        5
Name: ADMISSION_LOCATION, dtype: int64

In [892]:
#check if there are any missing values
variable6.ETHNICITY
variable6.ETHNICITY.isnull()

# Making a list of missing value types
missing_values = ["UNKNOWN/NOT SPECIFIED","UNABLE TO OBTAIN"]
variable6 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/ADMISSIONS.csv", na_values = missing_values)

In [893]:
variable6['ETHNICITY'].value_counts()

WHITE                                                       40996
BLACK/AFRICAN AMERICAN                                       5440
HISPANIC OR LATINO                                           1696
OTHER                                                        1512
ASIAN                                                        1509
PATIENT DECLINED TO ANSWER                                    559
ASIAN - CHINESE                                               277
HISPANIC/LATINO - PUERTO RICAN                                232
BLACK/CAPE VERDEAN                                            200
WHITE - RUSSIAN                                               164
MULTI RACE ETHNICITY                                          130
BLACK/HAITIAN                                                 101
ASIAN - ASIAN INDIAN                                           85
WHITE - OTHER EUROPEAN                                         81
HISPANIC/LATINO - DOMINICAN                                    78
PORTUGUESE                                                     61
WHITE - BRAZILIAN                                              59
ASIAN - VIETNAMESE                                             53
AMERICAN INDIAN/ALASKA NATIVE                                  51
BLACK/AFRICAN                                                  44
MIDDLE EASTERN                                                 43
HISPANIC/LATINO - GUATEMALAN                                   40
WHITE - EASTERN EUROPEAN                                       25
ASIAN - FILIPINO                                               25
HISPANIC/LATINO - CUBAN                                        24
HISPANIC/LATINO - SALVADORAN                                   19
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER                      18
ASIAN - CAMBODIAN                                              17
ASIAN - OTHER                                                  17
ASIAN - KOREAN                                                 13
HISPANIC/LATINO - MEXICAN                                      13
HISPANIC/LATINO - CENTRAL AMERICAN (OTHER)                     13
CARIBBEAN ISLAND                                                9
HISPANIC/LATINO - COLOMBIAN                                     9
SOUTH AMERICAN                                                  8
ASIAN - JAPANESE                                                7
ASIAN - THAI                                                    4
HISPANIC/LATINO - HONDURAN                                      4
AMERICAN INDIAN/ALASKA NATIVE FEDERALLY RECOGNIZED TRIBE        3
Name: ETHNICITY, dtype: int64

In [894]:
variable6['ETHNICITY'].isna().sum()

5337

In [895]:
# Replace using median 
#median = variable6['ETHNICITY'].median()
variable6['ETHNICITY'].fillna('WHITE', inplace=True)

In [896]:
variable6['ETHNICITY'].isna().sum()

0

In [897]:
variable6['DIAGNOSIS'].isna().sum() 
variable6['DIAGNOSIS'].value_counts()
# Replace using median 
#median = variable6['ETHNICITY'].median()
variable6['DIAGNOSIS'].fillna('FEVER', inplace=True)
variable6['DIAGNOSIS'].isna().sum()

0

In [898]:
variable7 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/CALLOUT.csv")
variable7.dtypes

ROW_ID                      int64
SUBJECT_ID                  int64
HADM_ID                     int64
SUBMIT_WARDID             float64
SUBMIT_CAREUNIT            object
CURR_WARDID               float64
CURR_CAREUNIT              object
CALLOUT_WARDID              int64
CALLOUT_SERVICE            object
REQUEST_TELE                int64
REQUEST_RESP                int64
REQUEST_CDIFF               int64
REQUEST_MRSA                int64
REQUEST_VRE                 int64
CALLOUT_STATUS             object
CALLOUT_OUTCOME            object
DISCHARGE_WARDID          float64
ACKNOWLEDGE_STATUS         object
CREATETIME                 object
UPDATETIME                 object
ACKNOWLEDGETIME            object
OUTCOMETIME                object
FIRSTRESERVATIONTIME       object
CURRENTRESERVATIONTIME     object
dtype: object

In [900]:
variable8 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/INPUTEVENTS_MV.csv")
variable8.count()

ROW_ID                           3618991
SUBJECT_ID                       3618991
HADM_ID                          3618991
ICUSTAY_ID                       3617827
STARTTIME                        3618991
ENDTIME                          3618991
ITEMID                           3618991
AMOUNT                           3618991
AMOUNTUOM                        3618991
RATE                             2042852
RATEUOM                          2042852
STORETIME                        3618991
CGID                             3618991
ORDERID                          3618991
LINKORDERID                      3618991
ORDERCATEGORYNAME                3618991
SECONDARYORDERCATEGORYNAME       2635563
ORDERCOMPONENTTYPEDESCRIPTION    3618991
ORDERCATEGORYDESCRIPTION         3618991
PATIENTWEIGHT                    3618991
TOTALAMOUNT                      3084964
TOTALAMOUNTUOM                   3088637
ISOPENBAG                        3618991
CONTINUEINNEXTDEPT               3618991
CANCELREASON                     3618991
STATUSDESCRIPTION                3618991
COMMENTS_EDITEDBY                 249261
COMMENTS_CANCELEDBY               119362
COMMENTS_DATE                     368625
ORIGINALAMOUNT                   3618991
ORIGINALRATE                     3618991
dtype: int64

In [901]:
variable9 = pd.read_csv("/Users/savitha/Desktop/PythonPractice/projectdata/TRANSFERS.csv")
variable9.dtypes

ROW_ID             int64
SUBJECT_ID         int64
HADM_ID            int64
ICUSTAY_ID       float64
DBSOURCE          object
EVENTTYPE         object
PREV_CAREUNIT     object
CURR_CAREUNIT     object
PREV_WARDID      float64
CURR_WARDID      float64
INTIME            object
OUTTIME           object
LOS              float64
dtype: object

In [902]:
variable1.count()

ROW_ID        27854055
SUBJECT_ID    27854055
HADM_ID       22245034
ITEMID        27854055
CHARTTIME     27854055
VALUE         27852810
VALUENUM      24932835
VALUEUOM      24753806
FLAG           9844166
dtype: int64

In [903]:
variable1.dtypes

ROW_ID          int64
SUBJECT_ID      int64
HADM_ID       float64
ITEMID          int64
CHARTTIME      object
VALUE          object
VALUENUM      float64
VALUEUOM       object
FLAG           object
dtype: object

In [904]:
df = pd.DataFrame(variable1)

In [905]:
#changing the datatype of HADM_ID from float to int
df['HADM_ID'] = df.HADM_ID.fillna(0).astype(int)

In [906]:
variable1.dtypes

ROW_ID          int64
SUBJECT_ID      int64
HADM_ID         int64
ITEMID          int64
CHARTTIME      object
VALUE          object
VALUENUM      float64
VALUEUOM       object
FLAG           object
dtype: object

In [907]:
num_lab_proc_variable = df.groupby(['SUBJECT_ID','HADM_ID'])['ITEMID'].count().reset_index(name='num_lab_procedures')
num_lab_proc_variable.head()

   SUBJECT_ID  HADM_ID  num_lab_procedures
0           2   163353                  47
1           3        0                 656
2           3   145834                1060
3           4        0                1409
4           4   185777                 245

In [908]:
#df.HADM_ID.value_counts().reset_index(name='num_lab_procedures')

In [909]:
#df.groupby(["HADM_ID"]).count().sort_values(["ITEMID"], 
 #   ascending=False).rename(columns={"ITEMID" : "num_lab_procedures"}).reset_index()

In [910]:
df1 = pd.DataFrame(variable2)

In [911]:
num_proc_varible = df1.groupby(['SUBJECT_ID','HADM_ID'])['ICD9_CODE'].count().reset_index(name='num_procedures')
num_proc_varible.head()

   SUBJECT_ID  HADM_ID  num_procedures
0           2   163353               1
1           3   145834               6
2           4   185777               3
3           5   178980               1
4           6   107064               5

In [912]:
variable3.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,STARTDATE,ENDDATE,DRUG_TYPE,DRUG,DRUG_NAME_POE,DRUG_NAME_GENERIC,FORMULARY_DRUG_CD,GSN,NDC,PROD_STRENGTH,DOSE_VAL_RX,DOSE_UNIT_RX,FORM_VAL_DISP,FORM_UNIT_DISP,ROUTE
0,2214776,6,107064,NaN,2175-06-11 00:00:00,2175-06-12 00:00:00,MAIN,Tacrolimus,Tacrolimus,Tacrolimus,TACR1,021796,469061711.0,1mg Capsule,2,mg,2,CAP,PO
1,2214775,6,107064,NaN,2175-06-11 00:00:00,2175-06-12 00:00:00,MAIN,Warfarin,Warfarin,Warfarin,WARF5,006562,56017275.0,5mg Tablet,5,mg,1,TAB,PO
2,2215524,6,107064,NaN,2175-06-11 00:00:00,2175-06-12 00:00:00,MAIN,Heparin Sodium,NaN,NaN,HEPAPREMIX,006522,338055002.0,"25,000 unit Premix Bag","25,000",UNIT,1,BAG,IV
3,2216265,6,107064,NaN,2175-06-11 00:00:00,2175-06-12 00:00:00,BASE,D5W,NaN,NaN,HEPBASE,NaN,0.0,HEPARIN BASE,250,ml,250,ml,IV
4,2214773,6,107064,NaN,2175-06-11 00:00:00,2175-06-12 00:00:00,MAIN,Furosemide,Furosemide,Furosemide,FURO20,008208,54829725.0,20mg Tablet,20,mg,1,TAB,PO

In [913]:
df2 = pd.DataFrame(variable3)

In [914]:
num_med_variable = df2.groupby(['SUBJECT_ID','HADM_ID'])['DRUG'].count().reset_index(name='num_medications')
num_med_variable.head()

   SUBJECT_ID  HADM_ID  num_medications
0           2   163353                4
1           4   185777               59
2           6   107064              148
3           8   159514                4
4           9   150750               68

In [915]:
df3 = pd.DataFrame(variable4)

In [916]:
number_diag_variable = df3.groupby('SUBJECT_ID')['ICD9_CODE'].count().reset_index(name='number_diagnoses')
number_diag_variable.head()

   SUBJECT_ID  number_diagnoses
0           2                 3
1           3                 9
2           4                 9
3           5                 3
4           6                 8

In [917]:
df4 = pd.DataFrame(variable5)

In [918]:
glu = variable5[variable5.LABEL == 'Glucose']
glu.head()

     ROW_ID  ITEMID    LABEL  FLUID    CATEGORY LOINC_CODE
136      10   50809  Glucose  Blood   Blood Gas     2339-0
258     132   50931  Glucose  Blood   Chemistry     2345-7
677     678   51478  Glucose  Urine  Hematology     5792-7

In [919]:
variable5.dtypes

ROW_ID         int64
ITEMID         int64
LABEL         object
FLUID         object
CATEGORY      object
LOINC_CODE    object
dtype: object

In [920]:
#Finding max_glu_serum itemid
glu = df4[df4.LABEL == 'Glucose']
glu_blood = glu[glu.FLUID == 'Blood']
glu_blood_gas = glu_blood[glu_blood.CATEGORY == 'Blood Gas']
df_glu_blood_gas = pd.DataFrame(glu_blood_gas)
#max_glu_serum_variable = df.HADM_ID[df.ITEMID == glu_blood_gas].reset_index(name='number_diagnoses')
#max_glu_serum_variable.head()

In [921]:
glu_blood_gas.dtypes

ROW_ID         int64
ITEMID         int64
LABEL         object
FLUID         object
CATEGORY      object
LOINC_CODE    object
dtype: object

In [922]:
variable1.dtypes

ROW_ID          int64
SUBJECT_ID      int64
HADM_ID         int64
ITEMID          int64
CHARTTIME      object
VALUE          object
VALUENUM      float64
VALUEUOM       object
FLAG           object
dtype: object

In [923]:
#Finding max_glu_serum's itemid from D_LABITEMS in LABEVENTS and fetching HADM_ID
max_glu_serum_temp = df[df['ITEMID'] == int(df_glu_blood_gas['ITEMID'])]
#max_glu_serum_temp.head()
max_glu_serum_temp = max_glu_serum_temp.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
#max_glu_serum_temp.head()
max_glu_serum_variable = max_glu_serum_temp.loc[:,['SUBJECT_ID','HADM_ID','ITEMID']]
max_glu_serum_variable.rename(columns={'ITEMID':'max_glu_serum'}, inplace=True)
#max_glu_serum_variable.columns
max_glu_serum_variable.head()

      SUBJECT_ID  HADM_ID  max_glu_serum
465            3   145834          50809
777            3        0          50809
1000           4        0          50809
3979           6   107064          50809
4380           9   150750          50809

In [924]:
#Finding A1Cresult itemid
A1Cresult = df4[df4.LABEL == '% Hemoglobin A1c']
df_A1Cresult = pd.DataFrame(A1Cresult)
#df_A1Cresult.head()

In [925]:
A1Cresult_temp = df[df['ITEMID'] == int(df_A1Cresult['ITEMID'])]
#A1Cresult_temp
A1Cresult_temp = A1Cresult_temp.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
#max_glu_serum_temp.head()
A1Cresult_variable = A1Cresult_temp.loc[:,['SUBJECT_ID','HADM_ID','ITEMID']]
A1Cresult_variable.rename(columns={'ITEMID':'A1Cresult'}, inplace=True)
A1Cresult_variable.head()

       SUBJECT_ID  HADM_ID  A1Cresult
2494            4        0      50852
4409            9   150750      50852
7931           17        0      50852
8533           18        0      50852
10311          23        0      50852

In [926]:
#Finding glyburide drug from prescriptions.csv
glyburide = df2[df2.DRUG.str.lower() == 'glyburide']
#glyburide.head()
df_glyburide = pd.DataFrame(glyburide.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_glyburide = df_glyburide.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_glyburide.rename(columns={'DRUG':'GlyBURIDE'}, inplace=True)
df_glyburide.head()

       SUBJECT_ID  HADM_ID  GlyBURIDE
1153           35   166707  GlyBURIDE
10561         163   138528  Glyburide
13726         191   136614  GlyBURIDE
18033         209   135807  Glyburide
24419         309   162308  GlyBURIDE

In [927]:
#Finding metformin drug from prescriptions.csv
metformin = df2[df2.DRUG.str.lower() == 'metformin']
#metformin.head()
df_metformin = pd.DataFrame(metformin.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_metformin = df_metformin.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_metformin.rename(columns={'DRUG':'Metformin'}, inplace=True)
df_metformin.head()

       SUBJECT_ID  HADM_ID  Metformin
482            13   143045  Metformin
2744           55   190665  Metformin
9768          137   151583  Metformin
16448         239   127976  Metformin
18034         209   135807  Metformin

In [928]:
#Finding pioglitazone drug from prescriptions.csv
pioglitazone = df2[df2.DRUG.str.lower() == 'pioglitazone']
#pioglitazone.head()
df_pioglitazone = pd.DataFrame(pioglitazone.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_pioglitazone = df_pioglitazone.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_pioglitazone.rename(columns={'DRUG':'pioglitazone'}, inplace=True)
df_pioglitazone.head()

         SUBJECT_ID  HADM_ID  pioglitazone
288968         3987   143224  Pioglitazone
589697         7393   181880  Pioglitazone
1174274       15832   114978  Pioglitazone
1239640       17260   180007  Pioglitazone
2115966       28555   151373  Pioglitazone

In [929]:
#Finding rosiglitazone drug from prescriptions.csv
rosiglitazone = df2[df2.DRUG.str.lower() == 'rosiglitazone maleate']
#rosiglitazone.head()
df_rosiglitazone = pd.DataFrame(rosiglitazone.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_rosiglitazone = df_rosiglitazone.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_rosiglitazone.rename(columns={'DRUG':'rosiglitazone'}, inplace=True)
df_rosiglitazone.head()

       SUBJECT_ID  HADM_ID          rosiglitazone
24426         309   162308  Rosiglitazone Maleate
34284         485   116665  Rosiglitazone Maleate
47628         642   130310  Rosiglitazone Maleate
48201         716   125161  Rosiglitazone Maleate
52525         708   168790  Rosiglitazone Maleate

In [930]:
#Finding insulin drug from prescriptions.csv
insulin = df2[df2.DRUG.str.lower() == 'insulin']
#insulin.head()
df_insulin = pd.DataFrame(insulin.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_insulin = df_insulin.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_insulin.rename(columns={'DRUG':'insulin'}, inplace=True)
df_insulin.head()

     SUBJECT_ID  HADM_ID  insulin
27           13   143045  Insulin
112           4   185777  Insulin
179           6   107064  Insulin
301          12   112213  Insulin
404          21   109451  Insulin

In [931]:
#Finding PChloride drug from prescriptions.csv
PChloride = df2[df2.DRUG.str.lower() == 'potassium chloride']
#PChloride.head()
df_PChloride = pd.DataFrame(PChloride.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_PChloride = df_PChloride.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_PChloride.rename(columns={'DRUG':'Potassium Chloride'}, inplace=True)
df_PChloride.head()

     SUBJECT_ID  HADM_ID  Potassium Chloride
34           13   143045  Potassium Chloride
77            9   150750  Potassium Chloride
120           4   185777  Potassium Chloride
288          12   112213  Potassium Chloride
363          21   109451  Potassium Chloride

In [932]:
#Finding D5W drug from prescriptions.csv
D5W = df2[df2.DRUG.str.lower() == 'd5w']
#D5W.head()
df_D5W = pd.DataFrame(D5W.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_D5W = df_D5W.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_D5W.rename(columns={'DRUG':'D5W'}, inplace=True)
df_D5W.head()

     SUBJECT_ID  HADM_ID  D5W
3             6   107064  D5W
23           13   143045  D5W
79            9   150750  D5W
126           4   185777  D5W
367          21   109451  D5W

In [933]:
#Finding Furosemide drug from prescriptions.csv
Furosemide = df2[df2.DRUG.str.lower() == 'furosemide']
#Furosemide.head()
df_Furosemide = pd.DataFrame(Furosemide.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_Furosemide = df_Furosemide.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_Furosemide.rename(columns={'DRUG':'Furosemide'}, inplace=True)
df_Furosemide.head()

     SUBJECT_ID  HADM_ID  Furosemide
4             6   107064  Furosemide
391          21   109451  Furosemide
463          13   143045  Furosemide
537          17   194023  Furosemide
791          25   129635  Furosemide

In [934]:
#Finding NS drug from prescriptions.csv
NS = df2[df2.DRUG.str.lower() == 'ns']
#NS.head()
df_NS = pd.DataFrame(NS.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_NS = df_NS.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_NS.rename(columns={'DRUG':'NS'}, inplace=True)
df_NS.head()

     SUBJECT_ID  HADM_ID  NS
84            9   150750  NS
158           4   185777  NS
191           6   107064  NS
284          12   112213  NS
423          21   109451  NS

In [935]:
#Finding Magnesium Sulfate drug from prescriptions.csv
MagSulfate = df2[df2.DRUG.str.lower() == 'magnesium sulfate']
#df_MagSulfate.head()
df_MagSulfate = pd.DataFrame(MagSulfate.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_MagSulfate = df_MagSulfate.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_MagSulfate.rename(columns={'DRUG':'Magnesium Sulfate'}, inplace=True)
df_MagSulfate.head()

     SUBJECT_ID  HADM_ID  Magnesium Sulfate
33           13   143045  Magnesium Sulfate
92            9   150750  Magnesium Sulfate
119           4   185777  Magnesium Sulfate
209           6   107064  Magnesium Sulfate
291          12   112213  Magnesium Sulfate

In [936]:
#Finding Heparin drug from prescriptions.csv
Heparin = df2[df2.DRUG.str.lower() == 'heparin']
#df_Heparin.head()
df_Heparin = pd.DataFrame(Heparin.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_Heparin = df_Heparin.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_Heparin.rename(columns={'DRUG':'Heparin'}, inplace=True)
df_Heparin.head()

     SUBJECT_ID  HADM_ID  Heparin
131           4   185777  Heparin
286          12   112213  Heparin
611          11   194540  Heparin
718          24   161859  Heparin
771          25   129635  Heparin

In [937]:
#Finding Acetaminophen drug from prescriptions.csv
Acetaminophen = df2[df2.DRUG.str.lower() == 'acetaminophen']
#df_Acetaminophen.head()
df_Acetaminophen = pd.DataFrame(Acetaminophen.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_Acetaminophen = df_Acetaminophen.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_Acetaminophen.rename(columns={'DRUG':'Acetaminophen'}, inplace=True)
df_Acetaminophen.head()

     SUBJECT_ID  HADM_ID  Acetaminophen
40           13   143045  Acetaminophen
130           4   185777  Acetaminophen
183           6   107064  Acetaminophen
493          17   194023  Acetaminophen
549          17   161087  Acetaminophen

In [938]:
#Finding Docusate Sodium drug from prescriptions.csv
DocSodium = df2[df2.DRUG.str.lower() == 'docusate sodium']
#DocSodium.head()
df_DocSodium = pd.DataFrame(DocSodium.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_DocSodium = df_DocSodium.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_DocSodium.rename(columns={'DRUG':'Docusate Sodium'}, inplace=True)
df_DocSodium.head()

     SUBJECT_ID  HADM_ID  Docusate Sodium
26           13   143045  Docusate Sodium
132           4   185777  Docusate Sodium
184           6   107064  Docusate Sodium
400          21   109451  Docusate Sodium
499          17   194023  Docusate Sodium

In [939]:
#Finding Aspirin drug from prescriptions.csv
Aspirin = df2[df2.DRUG.str.lower() == 'aspirin']
#Aspirin.head()
df_Aspirin = pd.DataFrame(Aspirin.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_Aspirin = df_Aspirin.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_Aspirin.rename(columns={'DRUG':'Aspirin'}, inplace=True)
df_Aspirin.head()

     SUBJECT_ID  HADM_ID  Aspirin
451          13   143045  Aspirin
496          17   194023  Aspirin
765          25   129635  Aspirin
823          21   111970  Aspirin
830          17   161087  Aspirin

In [940]:
#Finding Furosemide drug from prescriptions.csv
Furosemide = df2[df2.DRUG.str.lower() == 'furosemide']
#Furosemide.head()
df_Furosemide = pd.DataFrame(Furosemide.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_Furosemide = df_Furosemide.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_Furosemide.rename(columns={'DRUG':'Furosemide'}, inplace=True)
df_Furosemide.head()

     SUBJECT_ID  HADM_ID  Furosemide
4             6   107064  Furosemide
391          21   109451  Furosemide
463          13   143045  Furosemide
537          17   194023  Furosemide
791          25   129635  Furosemide

In [941]:
#Finding Pantoprazole drug from prescriptions.csv
Pantoprazole = df2[df2.DRUG.str.lower() == 'pantoprazole']
#Pantoprazole.head()
df_Pantoprazole = pd.DataFrame(Pantoprazole.loc[:,['SUBJECT_ID','HADM_ID','DRUG']])
df_Pantoprazole = df_Pantoprazole.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
df_Pantoprazole.rename(columns={'DRUG':'Pantoprazole'}, inplace=True)
df_Pantoprazole.head()

     SUBJECT_ID  HADM_ID  Pantoprazole
180           6   107064  Pantoprazole
351          12   112213  Pantoprazole
356          13   143045  Pantoprazole
401          21   109451  Pantoprazole
603          11   194540  Pantoprazole

In [942]:
#Finding patientweight from inputevents_mv.csv
mrg6 = variable8.loc[:,['SUBJECT_ID','HADM_ID','PATIENTWEIGHT']]
mrg6 = mrg6.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
mrg6.count()

SUBJECT_ID       21879
HADM_ID          21879
PATIENTWEIGHT    21879
dtype: int64

In [943]:
#Finding timeinhospital(LengthOfStay) from transfers.csv
mrg8 = variable9.loc[:,['SUBJECT_ID','HADM_ID','LOS']]
mrg8 = mrg8.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
mrg8.count()

SUBJECT_ID    58976
HADM_ID       58976
LOS           58765
dtype: int64

In [944]:
hosp_expire = variable6.loc[:,['SUBJECT_ID','HADM_ID','HOSPITAL_EXPIRE_FLAG']]
hosp_expire = hosp_expire.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'])
#expire.count()
expire = variable.loc[:,['SUBJECT_ID','EXPIRE_FLAG']]
expire_flag = hosp_expire.merge(expire, on = 'SUBJECT_ID', how='left')
expire_flag = expire_flag.drop_duplicates(subset=['SUBJECT_ID','EXPIRE_FLAG'], keep='last')
expire_flag.head()
#expire_variable = expire_flag.EXPIRE_FLAG.value_counts().reset_index(name='Moratility number')
#expire_variable

   SUBJECT_ID  HADM_ID  HOSPITAL_EXPIRE_FLAG  EXPIRE_FLAG
0          22   165315                     0            0
2          23   124321                     0            0
3          24   161859                     0            0
4          25   129635                     0            0
5          26   197661                     0            1

In [945]:
expire_flag['HOSPITAL_EXPIRE_FLAG'].isna().sum() 
expire_flag['HOSPITAL_EXPIRE_FLAG'].value_counts()
# Replace using median 
#median = expire_flag['HOSPITAL_EXPIRE_FLAG'].median()
#expire_flag['HOSPITAL_EXPIRE_FLAG'].fillna(median, inplace=True)
#expire_flag['HOSPITAL_EXPIRE_FLAG'].isna().sum()

0    40729
1     5791
Name: HOSPITAL_EXPIRE_FLAG, dtype: int64

In [946]:
import datetime
age_admit_time = variable6.loc[:,['SUBJECT_ID','ADMITTIME']]
age_cal_var = age_admit_time.groupby(['SUBJECT_ID'])['ADMITTIME'].min().reset_index(name='min_admit_time')
age_cal_var['min_admit_time'] = pd.to_datetime(age_cal_var.min_admit_time)
age_cal_var.head()
age_dob = variable.loc[:,['SUBJECT_ID','DOB']]
age_dob['DOB'] = pd.to_datetime(age_dob.DOB)
age_cal = age_cal_var.merge(age_dob, on = 'SUBJECT_ID', how='left')
age_cal.dtypes

SUBJECT_ID                 int64
min_admit_time    datetime64[ns]
DOB               datetime64[ns]
dtype: object

In [947]:
age_cal['Age'] = age_cal.min_admit_time.dt.year - age_cal.DOB.dt.year
age_cal.head()
age_final = age_cal.loc[:,['SUBJECT_ID','Age']]
age_final.head()

   SUBJECT_ID  Age
0           2    0
1           3   76
2           4   48
3           5    0
4           6   66

In [948]:
age_final['Age'].isna().sum() 
age_final['Age'].value_counts()
# Replace using median 
#median = age_final['Age'].median()
#age_final['Age'] = age_final['Age'].replace([0], 60)
#age_final['Age'].fillna(median, inplace=True)
#age_final['Age'].isna().sum()

0      7872
300    1991
77      887
79      854
69      836
78      833
72      823
60      817
81      812
80      807
66      805
68      790
64      789
75      781
62      775
76      774
63      770
82      766
65      760
67      760
74      758
61      754
70      748
73      747
59      746
71      738
58      737
83      735
84      731
57      704
       ...
42      319
41      317
40      294
39      271
38      260
89      231
37      225
35      221
34      193
22      191
33      187
36      185
24      177
21      177
26      174
23      171
32      168
30      166
25      164
29      161
20      161
28      160
31      160
27      156
19      141
18       94
17       49
16       11
15        8
1         2
Name: Age, Length: 78, dtype: int64

In [949]:
variable6.dtypes

ROW_ID                   int64
SUBJECT_ID               int64
HADM_ID                  int64
ADMITTIME               object
DISCHTIME               object
DEATHTIME               object
ADMISSION_TYPE          object
ADMISSION_LOCATION      object
DISCHARGE_LOCATION      object
INSURANCE               object
LANGUAGE                object
RELIGION                object
MARITAL_STATUS          object
ETHNICITY               object
EDREGTIME               object
EDOUTTIME               object
DIAGNOSIS               object
HOSPITAL_EXPIRE_FLAG     int64
HAS_CHARTEVENTS_DATA     int64
dtype: object

In [1113]:
#Calculate number of inpatients
import datetime
from datetime import timedelta
inpatient_variable = variable6.loc[:,['SUBJECT_ID','HADM_ID','ADMITTIME','ADMISSION_TYPE']]
#inpatient_variable
inpatient_variable = inpatient_variable[inpatient_variable.ADMISSION_TYPE.str.lower() != 'emergency']
#inpatient_variable.count()
inpatient_var = inpatient_variable.groupby(['SUBJECT_ID'])['ADMITTIME'].max().reset_index(name='max_admit_time')
inpatient_var['max_admit_time'] = pd.to_datetime(inpatient_var.max_admit_time)
inpatient_var['Admit_Range'] = inpatient_var.max_admit_time - pd.offsets.DateOffset(years=1)
#inpatient_var.head()
nip_mrg = inpatient_variable.merge(inpatient_var, on = 'SUBJECT_ID', how='left')
nip_mrg['ADMITTIME'] = pd.to_datetime(nip_mrg.ADMITTIME)
#nip_mrg
inpatient_var_final = nip_mrg[(nip_mrg['ADMITTIME'] >= nip_mrg['Admit_Range']) & (nip_mrg['ADMITTIME'] 
                                                                                  <= nip_mrg['max_admit_time'])]
inpatient_var_final = inpatient_var_final.sort_values(['SUBJECT_ID','HADM_ID'],ascending = True)
#inpatient_var_final.count()
num_inpat_variable = inpatient_var_final.groupby(['SUBJECT_ID'])['HADM_ID'].count().reset_index(name='num_inpatient')
num_inpat_variable.head()

   SUBJECT_ID  num_inpatient
0           2              1
1           5              1
2           6              1
3           7              1
4           8              1

In [1112]:
#Calculate number of emergency patients
import datetime
from datetime import timedelta
emerpatient_variable = variable6.loc[:,['SUBJECT_ID','HADM_ID','ADMITTIME','ADMISSION_TYPE']]
emerpatient_variable = emerpatient_variable[emerpatient_variable.ADMISSION_TYPE.str.lower() == 'emergency']
emerpatient_var = emerpatient_variable.groupby(['SUBJECT_ID'])['ADMITTIME'].max().reset_index(name='max_admit_time')
emerpatient_var['max_admit_time'] = pd.to_datetime(emerpatient_var.max_admit_time)
emerpatient_var['Admit_Range'] = emerpatient_var.max_admit_time - pd.offsets.DateOffset(years=1)
#emerpatient_var.head()
nep_mrg = emerpatient_variable.merge(emerpatient_var, on = 'SUBJECT_ID', how='left')
nep_mrg['ADMITTIME'] = pd.to_datetime(nep_mrg.ADMITTIME)
#nep_mrg
emerpatient_var_final = nep_mrg[(nep_mrg['ADMITTIME'] >= nep_mrg['Admit_Range']) & 
                                (nep_mrg['ADMITTIME'] <= nep_mrg['max_admit_time'])]
#emerpatient_var_final
emerpatient_var_final = emerpatient_var_final.sort_values(['SUBJECT_ID','HADM_ID'],ascending = True)
#emerpatient_var_final
num_emer_variable = emerpatient_var_final.groupby(['SUBJECT_ID'])['HADM_ID'].count().reset_index(name='num_emergency')
num_emer_variable.head()

   SUBJECT_ID  num_emergency
0           3              1
1           4              1
2           9              1
3          11              1
4          13              1

In [952]:
#Calculate readmitted 
import datetime
from datetime import timedelta
readmit_variable = variable6.loc[:,['SUBJECT_ID','HADM_ID','ADMITTIME','DISCHTIME']]
#readmit_var = readmit_variable.groupby(['SUBJECT_ID','DISCHTIME'])
readmit_variable['ADMITTIME'] = pd.to_datetime(readmit_variable.ADMITTIME)
readmit_variable['DISCHTIME'] = pd.to_datetime(readmit_variable.DISCHTIME)
readmit_variable['Admit_Range'] = readmit_variable.DISCHTIME + pd.offsets.DateOffset(months=1)
readmit_variable = readmit_variable.sort_values(['SUBJECT_ID','HADM_ID'],ascending = True)
 
readmit_variable['ADMITTIME_s']= readmit_variable['ADMITTIME'].shift(-1)
readmit_variable['SUBJECT_ID_s']= readmit_variable['SUBJECT_ID'].shift(-1).fillna(0).astype(int)
readmit_var_final = readmit_variable[(readmit_variable['ADMITTIME_s'] >= readmit_variable['DISCHTIME']) & 
                                    (readmit_variable['ADMITTIME_s'] <= readmit_variable['Admit_Range']) & 
                                     (readmit_variable['SUBJECT_ID_s'] == readmit_variable['SUBJECT_ID'])]
readmit_var_final['Readmit'] = readmit_var_final['SUBJECT_ID'] == readmit_var_final['SUBJECT_ID_s']

readmit_var = readmit_var_final.loc[:,['SUBJECT_ID','HADM_ID','Readmit']]
#readmit_variable
readmit_var.head()

/Users/savitha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

     SUBJECT_ID  HADM_ID  Readmit
108         103   130744     True
577         283   109185     True
583         287   174293     True
231         299   175259     True
306         356   135591     True

In [953]:
variable6.dtypes

ROW_ID                   int64
SUBJECT_ID               int64
HADM_ID                  int64
ADMITTIME               object
DISCHTIME               object
DEATHTIME               object
ADMISSION_TYPE          object
ADMISSION_LOCATION      object
DISCHARGE_LOCATION      object
INSURANCE               object
LANGUAGE                object
RELIGION                object
MARITAL_STATUS          object
ETHNICITY               object
EDREGTIME               object
EDOUTTIME               object
DIAGNOSIS               object
HOSPITAL_EXPIRE_FLAG     int64
HAS_CHARTEVENTS_DATA     int64
dtype: object

In [954]:
mrg1 = variable6.loc[:,['SUBJECT_ID','HADM_ID','ETHNICITY','ADMISSION_TYPE','ADMISSION_LOCATION',
                        'INSURANCE','DIAGNOSIS']]
#mrg1.count()
mrg2 = variable7.loc[:,['SUBJECT_ID','HADM_ID','DISCHARGE_WARDID']]
mrg2 = mrg2.drop_duplicates(subset=['SUBJECT_ID','HADM_ID'], keep='last')
#mrg2.count()
mrg3 = mrg1.merge(mrg2, on = ['SUBJECT_ID','HADM_ID'], how='left')
#mrg3.count()
exp_mrg = mrg3.merge(expire_flag, on = ['SUBJECT_ID','HADM_ID'], how='left')
#exp_mrg.dtypes
age_mrg = exp_mrg.merge(age_final, on = ['SUBJECT_ID'], how='left')
#age_mrg
#expire_variable = age_mrg.EXPIRE_FLAG.value_counts().reset_index(name='Moratility number')
#expire_variable

In [955]:
#df_mrg = pd.DataFrame(mrg3)
#df_mrg['SUBJECT_ID'] = df_mrg.SUBJECT_ID.fillna(0).astype(int)
#df_mrg['HADM_ID'] = df_mrg.HADM_ID.fillna(0).astype(int)
#df_mrg.dtypes
mrg4 = variable.loc[:,['SUBJECT_ID','GENDER']]
#mrg4.head()
mrg5 = age_mrg.merge(mrg4, on='SUBJECT_ID', how='left')
mrg5.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
dtype: int64

In [956]:
mrg7 = mrg5.merge(mrg6, on = ['SUBJECT_ID','HADM_ID'], how='left')
#mrg7.count() 
mrg_num_emer = mrg7.merge(num_emer_variable, on = ['SUBJECT_ID'], how='left') 
#mrg_num_emer.head() 
mrg_num_inpat = mrg_num_emer.merge(num_inpat_variable, on = ['SUBJECT_ID'], how='left') 
mrg_num_inpat.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
dtype: int64

In [957]:
mrg9 = mrg_num_inpat.merge(mrg8, on = ['SUBJECT_ID','HADM_ID'], how='left')
#mrg9.count()
mrg10 = mrg9.merge(num_lab_proc_variable, on = ['SUBJECT_ID','HADM_ID'], how='left')
#mrg10.count()
mrg11 = mrg10.merge(num_proc_varible, on = ['SUBJECT_ID','HADM_ID'], how='left')
#mrg11.count()
mrg12 = mrg11.merge(num_med_variable, on = ['SUBJECT_ID','HADM_ID'], how='left')
#mrg12.count()
mrg13 = mrg12.merge(number_diag_variable, on='SUBJECT_ID', how='left')
#mrg13.count()
mrg14 = mrg13.merge(max_glu_serum_variable, on = ['SUBJECT_ID','HADM_ID'], how='left')
mrg14.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
dtype: int64

In [958]:
mrg15 = mrg14.merge(A1Cresult_variable, on = ['SUBJECT_ID','HADM_ID'], how='left')
mrg16 = mrg15.merge(df_metformin, on = ['SUBJECT_ID','HADM_ID'], how='left')
mrg16.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
dtype: int64

In [959]:
PChloride_mrg = mrg16.merge(df_PChloride, on = ['SUBJECT_ID','HADM_ID'], how='left')
#PChloride_mrg.count()
D5W_mrg = PChloride_mrg.merge(df_D5W, on = ['SUBJECT_ID','HADM_ID'], how='left')
#D5W_mrg.count()
Furosemide_mrg = D5W_mrg.merge(df_Furosemide, on = ['SUBJECT_ID','HADM_ID'], how='left')
#Furosemide_mrg.count()
NS_mrg = Furosemide_mrg.merge(df_NS, on = ['SUBJECT_ID','HADM_ID'], how='left')
NS_mrg.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
dtype: int64

In [960]:
Heparin_mrg = NS_mrg.merge(df_Heparin, on = ['SUBJECT_ID','HADM_ID'], how='left')
Heparin_mrg.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
Heparin                 30847
dtype: int64

In [961]:
MagSulfate_mrg = Heparin_mrg.merge(df_MagSulfate, on = ['SUBJECT_ID','HADM_ID'], how='left')
#MagSulfate_mrg.count()
Pantoprazole_mrg = MagSulfate_mrg.merge(df_Pantoprazole, on = ['SUBJECT_ID','HADM_ID'], how='left')
#Pantoprazole_mrg.count()
Aspirin_mrg = Pantoprazole_mrg.merge(df_Aspirin, on = ['SUBJECT_ID','HADM_ID'], how='left')
#Aspirin_mrg.count()
DocSodium_mrg = Aspirin_mrg.merge(df_DocSodium, on = ['SUBJECT_ID','HADM_ID'], how='left')
#DocSodium_mrg.count()
Acetaminophen_mrg = DocSodium_mrg.merge(df_Acetaminophen, on = ['SUBJECT_ID','HADM_ID'], how='left')
Acetaminophen_mrg.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
Heparin                 30847
Magnesium Sulfate       31482
Pantoprazole            21276
Aspirin                 19271
Docusate Sodium         28423
Acetaminophen           35360
dtype: int64

In [962]:
mrg17 = Acetaminophen_mrg.merge(df_glyburide, on = ['SUBJECT_ID','HADM_ID'], how='left')
mrg17.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
Heparin                 30847
Magnesium Sulfate       31482
Pantoprazole            21276
Aspirin                 19271
Docusate Sodium         28423
Acetaminophen           35360
GlyBURIDE                1036
dtype: int64

In [963]:
mrg18 = mrg17.merge(df_pioglitazone, on = ['SUBJECT_ID','HADM_ID'], how='left')
mrg18.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
Heparin                 30847
Magnesium Sulfate       31482
Pantoprazole            21276
Aspirin                 19271
Docusate Sodium         28423
Acetaminophen           35360
GlyBURIDE                1036
pioglitazone              118
dtype: int64

In [964]:
mrg19 = mrg18.merge(df_rosiglitazone, on = ['SUBJECT_ID','HADM_ID'], how='left')
mrg19.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    46520
EXPIRE_FLAG             46520
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
Heparin                 30847
Magnesium Sulfate       31482
Pantoprazole            21276
Aspirin                 19271
Docusate Sodium         28423
Acetaminophen           35360
GlyBURIDE                1036
pioglitazone              118
rosiglitazone             283
dtype: int64

In [965]:
mrg20 = mrg19.merge(df_insulin, on = ['SUBJECT_ID','HADM_ID'], how='left')
mrg20.head()

,SUBJECT_ID,HADM_ID,ETHNICITY,ADMISSION_TYPE,ADMISSION_LOCATION,INSURANCE,DIAGNOSIS,DISCHARGE_WARDID,HOSPITAL_EXPIRE_FLAG,EXPIRE_FLAG,...,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,GlyBURIDE,pioglitazone,rosiglitazone,insulin
0,22,165315,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,BENZODIAZEPINE OVERDOSE,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,23,152223,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,NaN,NaN,NaN,...,NaN,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,NaN,NaN,Insulin
2,23,124321,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,BRAIN MASS,31.0,0.0,0.0,...,Heparin,Magnesium Sulfate,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,NaN,NaN,Insulin
3,24,161859,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Private,INTERIOR MYOCARDIAL INFARCTION,NaN,0.0,0.0,...,Heparin,NaN,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,NaN,NaN,Insulin
4,25,129635,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,ACUTE CORONARY SYNDROME,NaN,0.0,0.0,...,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,NaN,Acetaminophen,NaN,NaN,NaN,NaN

In [966]:
mrg20['HOSPITAL_EXPIRE_FLAG'] = mrg20.HOSPITAL_EXPIRE_FLAG.fillna(0).astype(int)
mrg20['EXPIRE_FLAG'] = mrg20.EXPIRE_FLAG.fillna(0).astype(int)

In [967]:
mrg21 = mrg20.merge(readmit_var, on = ['SUBJECT_ID','HADM_ID'], how='left')
mrg21.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    58976
EXPIRE_FLAG             58976
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
Heparin                 30847
Magnesium Sulfate       31482
Pantoprazole            21276
Aspirin                 19271
Docusate Sodium         28423
Acetaminophen           35360
GlyBURIDE                1036
pioglitazone              118
rosiglitazone             283
insulin                 31262
Readmit                  1197
dtype: int64

In [968]:
mrg21.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    58976
EXPIRE_FLAG             58976
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Metformin                 646
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
Heparin                 30847
Magnesium Sulfate       31482
Pantoprazole            21276
Aspirin                 19271
Docusate Sodium         28423
Acetaminophen           35360
GlyBURIDE                1036
pioglitazone              118
rosiglitazone             283
insulin                 31262
Readmit                  1197
dtype: int64

In [970]:
to_drop = ['Metformin',
            'pioglitazone',
            'rosiglitazone']
mrg21.drop(to_drop, inplace=True, axis=1)

In [971]:
mrg21.count()

SUBJECT_ID              58976
HADM_ID                 58976
ETHNICITY               58976
ADMISSION_TYPE          58976
ADMISSION_LOCATION      58976
INSURANCE               58976
DIAGNOSIS               58976
DISCHARGE_WARDID        28732
HOSPITAL_EXPIRE_FLAG    58976
EXPIRE_FLAG             58976
Age                     58976
GENDER                  58976
PATIENTWEIGHT           21879
num_emergency           44686
num_inpatient           20622
LOS                     58765
num_lab_procedures      58151
num_procedures          52243
num_medications         50216
number_diagnoses        58976
max_glu_serum           26717
A1Cresult                6615
Potassium Chloride      35768
D5W                     25407
Furosemide              23919
NS                      24725
Heparin                 30847
Magnesium Sulfate       31482
Pantoprazole            21276
Aspirin                 19271
Docusate Sodium         28423
Acetaminophen           35360
GlyBURIDE                1036
insulin                 31262
Readmit                  1197
dtype: int64

In [972]:
mrg21.index.get_values()

array([    0,     1,     2, ..., 58973, 58974, 58975])

In [973]:
mrg21.set_index('HADM_ID', inplace=True)

In [974]:
mrg21

,SUBJECT_ID,ETHNICITY,ADMISSION_TYPE,ADMISSION_LOCATION,INSURANCE,DIAGNOSIS,DISCHARGE_WARDID,HOSPITAL_EXPIRE_FLAG,EXPIRE_FLAG,Age,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,GlyBURIDE,insulin,Readmit
HADM_ID,,,,,,,,,,,,,,,,,,,,,
165315,22,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,BENZODIAZEPINE OVERDOSE,NaN,0,0,65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152223,23,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,NaN,0,0,71,...,NS,NaN,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
124321,23,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,BRAIN MASS,31.0,0,0,71,...,NaN,Heparin,Magnesium Sulfate,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
161859,24,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Private,INTERIOR MYOCARDIAL INFARCTION,NaN,0,0,39,...,NS,Heparin,NaN,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
129635,25,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,ACUTE CORONARY SYNDROME,NaN,0,0,59,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,NaN,Acetaminophen,NaN,NaN,NaN
197661,26,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,V-TACH,NaN,0,1,72,...,NaN,Heparin,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
134931,27,WHITE,NEWBORN,PHYS REFERRAL/NORMAL DELI,Private,NEWBORN,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162569,28,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,NaN,0,0,74,...,NS,NaN,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
104557,30,WHITE,URGENT,TRANSFER FROM HOSP/EXTRAM,Medicare,UNSTABLE ANGINA\CATH,NaN,0,0,300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128652,31,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,STATUS EPILEPTICUS,NaN,1,1,72,...,NS,Heparin,Magnesium Sulfate,NaN,Aspirin,NaN,Acetaminophen,NaN,Insulin,NaN
175413,32,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicaid,TRACHEAL STENOSIS/SDA,NaN,0,0,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176176,33,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,SEPSIS;TELEMETRY,NaN,0,0,82,...,NS,NaN,NaN,NaN,NaN,Docusate Sodium,Acetaminophen,NaN,NaN,NaN
115799,34,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,CHEST PAIN\CATH,2.0,0,0,300,...,NaN,NaN,NaN,NaN,NaN,NaN,Acetaminophen,NaN,NaN,NaN
144319,34,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,BRADYCARDIA,17.0,0,1,300,...,NaN,NaN,NaN,NaN,Aspirin,NaN,Acetaminophen,NaN,NaN,NaN
166707,35,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,AORTIC VALVE DISEASE\CORONARY ARTERY BYPASS GR...,NaN,0,0,70,...,NS,NaN,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,GlyBURIDE,Insulin,NaN
182104,36,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,55.0,0,0,70,...,NS,Heparin,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
122659,36,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,CHEST PAIN/SHORTNESS OF BREATH,55.0,0,0,70,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
165660,36,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,VENTRAL HERNIA/SDA,24.0,0,0,70,...,NaN,Heparin,NaN,Pantoprazole,Aspirin,NaN,Acetaminophen,NaN,NaN,NaN
188670,37,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,CONGESTIVE HEART FAILURE,NaN,0,1,69,...,NS,Heparin,NaN,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
185910,38,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,ACUTE MYOCARDIAL INFARCTION-SEPSIS,NaN,0,0,76,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
106266,39,WHITE,NEWBORN,PHYS REFERRAL/NORMAL DELI,Private,NEWBORN,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101757,41,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,RIGHT BRAIN STEM LESION/SDA,3.0,0,1,56,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
174486,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,GASTROINTESTINAL BLEED,54.0,0,0,62,...,NS,NaN,Magnesium Sulfate,Pantoprazole,NaN,NaN,Acetaminophen,NaN,Insulin,NaN
145674,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,SEIZURE,3.0,0,0,62,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,NaN,NaN,Acetaminophen,NaN,Insulin,NaN
122609,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,SEPSIS,NaN,0,0,62,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,NaN,NaN,NaN,NaN,Insulin,NaN
101651,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,PNEUMONIA,55.0,0,0,62,...,NaN,Heparin,NaN,NaN,NaN,NaN,NaN,NaN,Insulin,NaN
117876,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,ALTERED MENTAL STATUS,31.0,0,1,62,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,NaN,NaN,NaN,Insulin,NaN
110872,358,WHITE,NEWBORN,PHYS REFERRAL/NORMAL DELI,Private,NEWBORN,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144265,359,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Self Pay,R/O MYOCARDIAL INFARCTION,NaN,0,0,49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154871,360,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,CEREBROVASCULAR ACCIDENT;TELEMETRY,NaN,0,0,76,...,NS,NaN,Magnesium Sulfate,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186076,98744,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,BLADDER MASS/SDA,24.0,0,0,69,...,NS,Heparin,Magnesium Sulfate,NaN,Aspirin,NaN,Acetaminophen,NaN,NaN,NaN
156671,98744,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,HYDRATION; PAIN MANAGEMENT; INFECTION,18.0,0,0,69,...,NS,Heparin,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,NaN,NaN
168288,98744,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,FEVER,24.0,0,0,69,...,NaN,Heparin,Magnesium Sulfate,Pantoprazole,NaN,NaN,Acetaminophen,NaN,NaN,True
116892,98744,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,RIGHT URETERAL STRICTURE/SDA,NaN,0,0,69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184410,98744,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,ABDOMINAL PAIN,24.0,0,0,69,...,NS,Heparin,Magnesium Sulfate,NaN,NaN,NaN,Acetaminophen,NaN,NaN,NaN
153703,98744,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,SEPSIS,24.0,0,0,69,...,NS,Heparin,Magnesium Sulfate,NaN,NaN,Docusate Sodium,Acetaminophen,NaN,NaN,NaN
104396,98744,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,BILATERAL URETERAL OBSTRUCTION/SDA,24.0,0,0,69,...,NaN,NaN,NaN,Pantoprazole,NaN,Docusate Sodium,NaN,NaN,NaN,NaN
150868,98746,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Private,LOWER GI BLEED,18.0,0,0,66,...,NaN,NaN,NaN,Pantoprazole,NaN,NaN,Acetaminophen,NaN,NaN,NaN
122488,98748,HISPANIC OR LATINO,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,NaN,0,0,82,...,NaN,NaN,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
158912,98749,BLACK/AFRICAN AMERICAN,EMERGENCY,EMERGENCY ROOM ADMIT,Medicaid,DIABETIC KETOACIDOSIS,45.0,0,0,37,...,NaN,Heparin,Magnesium Sulfate,NaN,NaN,Docusate Sodium,NaN,NaN,Insulin,NaN
156499,98751,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,HYPOTENSION,4.0,0,0,61,...,NaN,NaN,Magnesium Sulfate,Pantoprazole,NaN,NaN,Acetaminophen,NaN,Insulin,NaN
185764,98753,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,R/O METASTASIS,18.0,1,1,78,...,NS,Heparin,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,NaN,NaN
184156,98755,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,ASTHMA/COPD EXACERBATION,NaN,0,1,80,...,NaN,Heparin,NaN,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
182231,98758,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,CHIARI MALFORMATION/SDA,31.0,0,0,31,...,NaN,Heparin,NaN,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
109836,98759,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Private,BRAIN ANEURYSM,31.0,0,0,69,...,NaN,Heparin,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,True
175386,98759,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,BRAIN ANEURYSM/SDA,31.0,0,0,69,...,NaN,NaN,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,NaN,NaN,Insulin,NaN
184477,98761,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,GASTROPARESIS\PLACEMENT OF G-TUBE **REMOTE WES...,NaN,0,0,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182540,98761,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,SHORT GUT SYNDROME/SDA,NaN,0,0,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175884,98761,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,DEHYDRATION,29.0,0,0,48,...,NaN,NaN,NaN,NaN,NaN,Docusate Sodium,NaN,NaN,NaN,NaN
192767,98762,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,ACUTE RENAL FAILURE,54.0,0,1,53,...,NaN,Heparin,Magnesium Sulfate,NaN,NaN,Docusate Sodium,Acetaminophen,NaN,NaN,NaN
127022,98768,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,LEUKOCYTOSIS,NaN,1,1,85,...,NaN,NaN,NaN,NaN,NaN,NaN,Acetaminophen,NaN,Insulin,NaN
141860,98769,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,ISCHEMIC COLITIS,40.0,0,1,81,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,NaN,NaN,Acetaminophen,NaN,Insulin,NaN
187987,98790,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,JOINT EFFUSION,49.0,0,0,53,...,NaN,Heparin,Magnesium Sulfate,NaN,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
190603,98794,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,AORTIC STENOSIS\AORTIC VALVE REPLACEMENT /SDA,2.0,0,0,78,...,NaN,NaN,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
105447,98797,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,ALTERED MENTAL STATUS,NaN,1,1,88,...,NS,NaN,NaN,NaN,NaN,Docusate Sodium,Acetaminophen,NaN,NaN,NaN
191113,98800,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Private,TRAUMA,40.0,0,0,20,...,NaN,Heparin,Magnesium Sulfate,NaN,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
101071,98802,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,SAH,NaN,1,1,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122631,98805,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,RENAL CANCER/SDA,24.0,0,0,42,...,NaN,Heparin,NaN,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
170407,98813,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,S/P FALL,40.0,0,0,60,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
190264,98813,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Private,INTRACRANIAL HEMORRHAGE,31.0,0,0,60,...,NaN,NaN,NaN,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,NaN,NaN

In [975]:
mrg21.index.get_values()

array([165315, 152223, 124321, ..., 122631, 170407, 190264])

In [987]:
mrg21['DISCHARGE_WARDID'].isna().sum() 
mrg21['DISCHARGE_WARDID'].value_counts()
# Replace using median 
median = mrg21['DISCHARGE_WARDID'].median()
mrg21['DISCHARGE_WARDID'].fillna(median, inplace=True)
mrg21['DISCHARGE_WARDID'].isna().sum()

0

In [988]:
mrg21['PATIENTWEIGHT'].isna().sum() 
mrg21['PATIENTWEIGHT'].value_counts()
# Replace using median 
median = mrg21['PATIENTWEIGHT'].median()
median
mrg21['PATIENTWEIGHT'].fillna(median, inplace=True)
#mrg21['PATIENTWEIGHT'].value_counts()

In [989]:
mrg21.head()

,SUBJECT_ID,ETHNICITY,ADMISSION_TYPE,ADMISSION_LOCATION,INSURANCE,DIAGNOSIS,DISCHARGE_WARDID,HOSPITAL_EXPIRE_FLAG,EXPIRE_FLAG,Age,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,GlyBURIDE,insulin,Readmit
HADM_ID,,,,,,,,,,,,,,,,,,,,,
165315,22,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,BENZODIAZEPINE OVERDOSE,31.0,0,0,65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152223,23,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,31.0,0,0,71,...,NS,NaN,Magnesium Sulfate,NaN,Aspirin,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
124321,23,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,BRAIN MASS,31.0,0,0,71,...,NaN,Heparin,Magnesium Sulfate,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
161859,24,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Private,INTERIOR MYOCARDIAL INFARCTION,31.0,0,0,39,...,NS,Heparin,NaN,Pantoprazole,NaN,Docusate Sodium,Acetaminophen,NaN,Insulin,NaN
129635,25,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,ACUTE CORONARY SYNDROME,31.0,0,0,59,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,NaN,Acetaminophen,NaN,NaN,NaN

In [1001]:
mrg21['num_emergency'].isna().sum() 
mrg21['num_emergency'].value_counts()
# Replace using median 
median = mrg21['num_emergency'].median()
median
mrg21['num_emergency'].fillna(median, inplace=True)
#mrg21['num_emergency'].isna().sum()

0

In [1007]:
mrg21['num_inpatient'].isna().sum() 
mrg21['num_inpatient'].value_counts()
# Replace using median 
median = mrg21['num_inpatient'].median()
median
mrg21['num_inpatient'].fillna(median, inplace=True)
mrg21['num_emergency'].isna().sum()

0

In [1012]:
mrg21['LOS'].isna().sum() 
mrg21['LOS'].value_counts()
# Replace using median 
median = mrg21['LOS'].median()
median
mrg21['LOS'].fillna(median, inplace=True)
mrg21['LOS'].isna().sum()

0

In [1016]:
mrg21['num_lab_procedures'].isna().sum() 
mrg21['num_lab_procedures'].value_counts()
# Replace using median 
median = mrg21['num_lab_procedures'].median()
median
mrg21['num_lab_procedures'].fillna(median, inplace=True)
mrg21['num_lab_procedures'].isna().sum()

0

In [1020]:
mrg21['num_procedures'].isna().sum() 
mrg21['num_procedures'].value_counts()
# Replace using median 
median = mrg21['num_procedures'].median()
median
mrg21['num_procedures'].fillna(median, inplace=True)
mrg21['num_procedures'].isna().sum()

0

In [1024]:
mrg21['num_medications'].isna().sum() 
mrg21['num_medications'].value_counts()
# Replace using median 
median = mrg21['num_medications'].median()
median
mrg21['num_medications'].fillna(median, inplace=True)
mrg21['num_medications'].isna().sum()

0

In [1037]:
mrg21['number_diagnoses'].isna().sum() 
#mrg21['number_diagnoses'].value_counts()
# Replace using median 
#median = mrg21['number_diagnoses'].median()
#median
#mrg21['number_diagnoses'].fillna(median, inplace=True)
#mrg21['number_diagnoses'].isna().sum()

0

In [1038]:
#max_glu_serum
mrg21['max_glu_serum'].isna().sum() 
mrg21['max_glu_serum'].value_counts()
# Replace using 0 
mrg21['max_glu_serum'].fillna(0, inplace=True)
mrg21['max_glu_serum'].isna().sum()

0

In [1045]:
mrg21['A1Cresult'].isna().sum() 
mrg21['A1Cresult'].value_counts()
# Replace using median 
#median = mrg21['A1Cresult'].median()
#median
mrg21['A1Cresult'].fillna(0, inplace=True)
mrg21['A1Cresult'].isna().sum()

0

In [1048]:
mrg21['Potassium Chloride'].isna().sum() 
mrg21['Potassium Chloride'].value_counts()
# Replace using median 
#median = mrg21['Potassium Chloride'].median()
#median
mrg21['Potassium Chloride'].fillna(0, inplace=True)
mrg21['Potassium Chloride'].isna().sum()

0

In [1051]:
mrg21['D5W'].isna().sum() 
mrg21['D5W'].value_counts()
# Replace using median 
#median = mrg21['Potassium Chloride'].median()
#median
mrg21['D5W'].fillna(0, inplace=True)
mrg21['D5W'].isna().sum()

0

In [1060]:
mrg21['Furosemide'].isna().sum() 
mrg21['Furosemide'].value_counts()
# Replace using median 
#median = mrg21['Furosemide'].median()
#median
mrg21['Furosemide'].fillna(0, inplace=True)
mrg21['Furosemide'].isna().sum()


mrg21['NS'].isna().sum() 
mrg21['NS'].value_counts()
# Replace using median 
#median = mrg21['NS'].median()
#median
mrg21['NS'].fillna(0, inplace=True)
mrg21['NS'].isna().sum()

0

In [1064]:
mrg21['Heparin'].isna().sum() 
mrg21['Heparin'].value_counts()
# Replace using median 
#median = mrg21['Heparin'].median()
#median
mrg21['Heparin'].fillna(0, inplace=True)
mrg21['Heparin'].isna().sum()

0

In [1071]:
mrg21['Magnesium Sulfate'].isna().sum() 
mrg21['Magnesium Sulfate'].value_counts()
# Replace using median 
#median = mrg21['Magnesium Sulfate'].median()
#median
mrg21['Magnesium Sulfate'].fillna(0, inplace=True)
mrg21['Magnesium Sulfate'].isna().sum()

0

In [1073]:
mrg21['Pantoprazole'].isna().sum() 
mrg21['Pantoprazole'].value_counts()
# Replace using median 
#median = mrg21['Pantoprazole'].median()
#median
mrg21['Pantoprazole'].fillna(0, inplace=True)
mrg21['Pantoprazole'].isna().sum()

0

In [1074]:
mrg21['Aspirin'].isna().sum() 
mrg21['Aspirin'].value_counts()
# Replace using median 
#median = mrg21['Aspirin'].median()
#median
mrg21['Aspirin'].fillna(0, inplace=True)
mrg21['Aspirin'].isna().sum()

0

In [1075]:
mrg21['Docusate Sodium'].isna().sum() 
mrg21['Docusate Sodium'].value_counts()
# Replace using median 
#median = mrg21['Docusate Sodium'].median()
#median
mrg21['Docusate Sodium'].fillna(0, inplace=True)
mrg21['Docusate Sodium'].isna().sum()

0

In [1076]:
mrg21['Acetaminophen'].isna().sum() 
mrg21['Acetaminophen'].value_counts()
# Replace using median 
#median = mrg21['Docusate Sodium'].median()
#median
mrg21['Acetaminophen'].fillna(0, inplace=True)
mrg21['Acetaminophen'].isna().sum()

0

In [1077]:
mrg21['GlyBURIDE'].isna().sum() 
mrg21['GlyBURIDE'].value_counts()
# Replace using median 
#median = mrg21['Docusate Sodium'].median()
#median
mrg21['GlyBURIDE'].fillna(0, inplace=True)
mrg21['GlyBURIDE'].isna().sum()

0

In [1080]:
mrg21['insulin'].isna().sum() 
mrg21['insulin'].value_counts()
# Replace using median 
#median = mrg21['Docusate Sodium'].median()
#median
mrg21['insulin'].fillna(0, inplace=True)
mrg21['insulin'].isna().sum()

0

In [1085]:
mrg21['Readmit'].isna().sum() 
mrg21['Readmit'].value_counts()
# Replace using median 
#median = mrg21['Docusate Sodium'].median()
#median
mrg21['Readmit'].fillna(0, inplace=True)
mrg21['Readmit'].isna().sum()

0

In [1087]:
#Moratility count
expire_variable = mrg21.HOSPITAL_EXPIRE_FLAG.value_counts().reset_index(name='Moratility number')
expire_variable

   index  Moratility number
0      0              53185
1      1               5791

In [1088]:
expire_variable = mrg21.EXPIRE_FLAG.value_counts().reset_index(name='Moratility number')
expire_variable

   index  Moratility number
0      0              43217
1      1              15759

In [1089]:
h = variable3.drop_duplicates(subset=['SUBJECT_ID','DRUG'])
#h['DRUG'].value_counts()

In [1090]:
mrg21

,SUBJECT_ID,ETHNICITY,ADMISSION_TYPE,ADMISSION_LOCATION,INSURANCE,DIAGNOSIS,DISCHARGE_WARDID,HOSPITAL_EXPIRE_FLAG,EXPIRE_FLAG,Age,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,GlyBURIDE,insulin,Readmit
HADM_ID,,,,,,,,,,,,,,,,,,,,,
165315,22,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,BENZODIAZEPINE OVERDOSE,31.0,0,0,65,...,0,0,0,0,0,0,0,0,0,0
152223,23,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,31.0,0,0,71,...,NS,0,Magnesium Sulfate,0,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
124321,23,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,BRAIN MASS,31.0,0,0,71,...,0,Heparin,Magnesium Sulfate,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,Insulin,0
161859,24,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Private,INTERIOR MYOCARDIAL INFARCTION,31.0,0,0,39,...,NS,Heparin,0,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,Insulin,0
129635,25,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,ACUTE CORONARY SYNDROME,31.0,0,0,59,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,0,Acetaminophen,0,0,0
197661,26,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,V-TACH,31.0,0,1,72,...,0,Heparin,Magnesium Sulfate,0,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
134931,27,WHITE,NEWBORN,PHYS REFERRAL/NORMAL DELI,Private,NEWBORN,31.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
162569,28,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,31.0,0,0,74,...,NS,0,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
104557,30,WHITE,URGENT,TRANSFER FROM HOSP/EXTRAM,Medicare,UNSTABLE ANGINA\CATH,31.0,0,0,300,...,0,0,0,0,0,0,0,0,0,0
128652,31,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,STATUS EPILEPTICUS,31.0,1,1,72,...,NS,Heparin,Magnesium Sulfate,0,Aspirin,0,Acetaminophen,0,Insulin,0
175413,32,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicaid,TRACHEAL STENOSIS/SDA,31.0,0,0,46,...,0,0,0,0,0,0,0,0,0,0
176176,33,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,SEPSIS;TELEMETRY,31.0,0,0,82,...,NS,0,0,0,0,Docusate Sodium,Acetaminophen,0,0,0
115799,34,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,CHEST PAIN\CATH,2.0,0,0,300,...,0,0,0,0,0,0,Acetaminophen,0,0,0
144319,34,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,BRADYCARDIA,17.0,0,1,300,...,0,0,0,0,Aspirin,0,Acetaminophen,0,0,0
166707,35,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,AORTIC VALVE DISEASE\CORONARY ARTERY BYPASS GR...,31.0,0,0,70,...,NS,0,Magnesium Sulfate,0,Aspirin,Docusate Sodium,Acetaminophen,GlyBURIDE,Insulin,0
182104,36,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,55.0,0,0,70,...,NS,Heparin,Magnesium Sulfate,0,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
122659,36,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,CHEST PAIN/SHORTNESS OF BREATH,55.0,0,0,70,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
165660,36,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,VENTRAL HERNIA/SDA,24.0,0,0,70,...,0,Heparin,0,Pantoprazole,Aspirin,0,Acetaminophen,0,0,0
188670,37,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,CONGESTIVE HEART FAILURE,31.0,0,1,69,...,NS,Heparin,0,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,Insulin,0
185910,38,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,ACUTE MYOCARDIAL INFARCTION-SEPSIS,31.0,0,0,76,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
106266,39,WHITE,NEWBORN,PHYS REFERRAL/NORMAL DELI,Private,NEWBORN,31.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101757,41,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,RIGHT BRAIN STEM LESION/SDA,3.0,0,1,56,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,Insulin,0
174486,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,GASTROINTESTINAL BLEED,54.0,0,0,62,...,NS,0,Magnesium Sulfate,Pantoprazole,0,0,Acetaminophen,0,Insulin,0
145674,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,SEIZURE,3.0,0,0,62,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,0,0,Acetaminophen,0,Insulin,0
122609,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,SEPSIS,31.0,0,0,62,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,0,0,0,0,Insulin,0
101651,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,PNEUMONIA,55.0,0,0,62,...,0,Heparin,0,0,0,0,0,0,Insulin,0
117876,357,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,ALTERED MENTAL STATUS,31.0,0,1,62,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,0,0,0,Insulin,0
110872,358,WHITE,NEWBORN,PHYS REFERRAL/NORMAL DELI,Private,NEWBORN,31.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
144265,359,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Self Pay,R/O MYOCARDIAL INFARCTION,31.0,0,0,49,...,0,0,0,0,0,0,0,0,0,0
154871,360,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,CEREBROVASCULAR ACCIDENT;TELEMETRY,31.0,0,0,76,...,NS,0,Magnesium Sulfate,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,Insulin,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186076,98744,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,BLADDER MASS/SDA,24.0,0,0,69,...,NS,Heparin,Magnesium Sulfate,0,Aspirin,0,Acetaminophen,0,0,0
156671,98744,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,HYDRATION; PAIN MANAGEMENT; INFECTION,18.0,0,0,69,...,NS,Heparin,Magnesium Sulfate,0,Aspirin,Docusate Sodium,Acetaminophen,0,0,0
168288,98744,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,FEVER,24.0,0,0,69,...,0,Heparin,Magnesium Sulfate,Pantoprazole,0,0,Acetaminophen,0,0,True
116892,98744,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,RIGHT URETERAL STRICTURE/SDA,31.0,0,0,69,...,0,0,0,0,0,0,0,0,0,0
184410,98744,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,ABDOMINAL PAIN,24.0,0,0,69,...,NS,Heparin,Magnesium Sulfate,0,0,0,Acetaminophen,0,0,0
153703,98744,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,SEPSIS,24.0,0,0,69,...,NS,Heparin,Magnesium Sulfate,0,0,Docusate Sodium,Acetaminophen,0,0,0
104396,98744,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,BILATERAL URETERAL OBSTRUCTION/SDA,24.0,0,0,69,...,0,0,0,Pantoprazole,0,Docusate Sodium,0,0,0,0
150868,98746,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Private,LOWER GI BLEED,18.0,0,0,66,...,0,0,0,Pantoprazole,0,0,Acetaminophen,0,0,0
122488,98748,HISPANIC OR LATINO,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,31.0,0,0,82,...,0,0,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
158912,98749,BLACK/AFRICAN AMERICAN,EMERGENCY,EMERGENCY ROOM ADMIT,Medicaid,DIABETIC KETOACIDOSIS,45.0,0,0,37,...,0,Heparin,Magnesium Sulfate,0,0,Docusate Sodium,0,0,Insulin,0
156499,98751,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,HYPOTENSION,4.0,0,0,61,...,0,0,Magnesium Sulfate,Pantoprazole,0,0,Acetaminophen,0,Insulin,0
185764,98753,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,R/O METASTASIS,18.0,1,1,78,...,NS,Heparin,Magnesium Sulfate,0,Aspirin,Docusate Sodium,Acetaminophen,0,0,0
184156,98755,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,ASTHMA/COPD EXACERBATION,31.0,0,1,80,...,0,Heparin,0,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,Insulin,0
182231,98758,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,CHIARI MALFORMATION/SDA,31.0,0,0,31,...,0,Heparin,0,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,Insulin,0
109836,98759,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Private,BRAIN ANEURYSM,31.0,0,0,69,...,0,Heparin,Magnesium Sulfate,0,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,True
175386,98759,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,BRAIN ANEURYSM/SDA,31.0,0,0,69,...,0,0,Magnesium Sulfate,0,Aspirin,Docusate Sodium,0,0,Insulin,0
184477,98761,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,GASTROPARESIS\PLACEMENT OF G-TUBE **REMOTE WES...,31.0,0,0,48,...,0,0,0,0,0,0,0,0,0,0
182540,98761,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,SHORT GUT SYNDROME/SDA,31.0,0,0,48,...,0,0,0,0,0,0,0,0,0,0
175884,98761,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,DEHYDRATION,29.0,0,0,48,...,0,0,0,0,0,Docusate Sodium,0,0,0,0
192767,98762,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,ACUTE RENAL FAILURE,54.0,0,1,53,...,0,Heparin,Magnesium Sulfate,0,0,Docusate Sodium,Acetaminophen,0,0,0
127022,98768,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,LEUKOCYTOSIS,31.0,1,1,85,...,0,0,0,0,0,0,Acetaminophen,0,Insulin,0
141860,98769,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,ISCHEMIC COLITIS,40.0,0,1,81,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,0,0,Acetaminophen,0,Insulin,0
187987,98790,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,JOINT EFFUSION,49.0,0,0,53,...,0,Heparin,Magnesium Sulfate,0,0,Docusate Sodium,Acetaminophen,0,Insulin,0
190603,98794,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,AORTIC STENOSIS\AORTIC VALVE REPLACEMENT /SDA,2.0,0,0,78,...,0,0,Magnesium Sulfate,0,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
105447,98797,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,ALTERED MENTAL STATUS,31.0,1,1,88,...,NS,0,0,0,0,Docusate Sodium,Acetaminophen,0,0,0
191113,98800,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Private,TRAUMA,40.0,0,0,20,...,0,Heparin,Magnesium Sulfate,0,0,Docusate Sodium,Acetaminophen,0,Insulin,0
101071,98802,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Medicare,SAH,31.0,1,1,84,...,0,0,0,0,0,0,0,0,0,0
122631,98805,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,RENAL CANCER/SDA,24.0,0,0,42,...,0,Heparin,0,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,Insulin,0
170407,98813,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,S/P FALL,40.0,0,0,60,...,NS,Heparin,Magnesium Sulfate,Pantoprazole,Aspirin,Docusate Sodium,Acetaminophen,0,Insulin,0
190264,98813,WHITE,EMERGENCY,CLINIC REFERRAL/PREMATURE,Private,INTRACRANIAL HEMORRHAGE,31.0,0,0,60,...,0,0,0,Pantoprazole,0,Docusate Sodium,Acetaminophen,0,0,0

In [1114]:
mrg21.dtypes

SUBJECT_ID                int64
ETHNICITY                object
ADMISSION_TYPE           object
ADMISSION_LOCATION       object
INSURANCE                object
DIAGNOSIS                object
DISCHARGE_WARDID        float64
HOSPITAL_EXPIRE_FLAG      int64
EXPIRE_FLAG               int64
Age                       int64
GENDER                   object
PATIENTWEIGHT           float64
num_emergency           float64
num_inpatient           float64
LOS                     float64
num_lab_procedures      float64
num_procedures          float64
num_medications         float64
number_diagnoses          int64
max_glu_serum           float64
A1Cresult               float64
Potassium Chloride       object
D5W                      object
Furosemide               object
NS                       object
Heparin                  object
Magnesium Sulfate        object
Pantoprazole             object
Aspirin                  object
Docusate Sodium          object
Acetaminophen            object
GlyBURIDE                object
insulin                  object
Readmit                  object
dtype: object